### ISSUE TITLE
How to manually unsubscribe after an `  useSubscription`  ?

### ISSUE THREAD

**Issue by dlight** [oscartbeaumont/rspc#112]
So, the [useSubscription in the @rspc/react package](https://github.com/oscartbeaumont/rspc/blob/v0.1.2/packages/react/src/index.tsx#L289-L337) internally defines an `unsubscribe`   function (which I presume that will be called when navigating to another page), but it appears to not expose it (`useSubscription`   returns void). Is there a way to call it myself?

**Comment by oscartbeaumont** [comment]
`@rspc/react` is designed to be an opinionated implementation that ties the underlying `@rspc/client` into the React & React Query lifecycle to provide a better DX. If you have special requirements there is nothing stopping you from using `@rspc/client` directly and creating your own wrapper. This will expose the unsubscribe function.

What is your use case for manually unsubscribing?

**Comment by dlight** [comment]
> If you have special requirements there is nothing stopping you from using @rspc/client directly and creating your own wrapper.

Fair enough!

> What is your use case for manually unsubscribing?

There's lots of data being streamed, and if the page is idle & in the background I would like to stop the feed, and restart only when the user come back, but without unloading any React component (because this would just make things slower when getting back to the page)

**Comment by oscartbeaumont** [comment]
I think I added an `enabled` flag (I know tRPC have this) which you could tie into a `const [enabled, setEnabled] = useState(false)` to control it. I haven't tested if it properly unsubscribes when you set enabled `false` and if it doesn't (which I would kinda expect to be honest) I can look into it because it's a bug.

The `enabled` flag might only be in `main`, not sure if it's been released yet.
