### ISSUE TITLE
Integrate subscriptions with TanStack Query

### ISSUE THREAD

**Issue by dlight** [oscartbeaumont/rspc#113]
So this one is tricky. As I mentioned [here](https://github.com/oscartbeaumont/rspc/issues/107#issuecomment-1377213479) websockets don't have first-class support in react-query. But with some boilerplate though (and some discipline on what goes on the websocket - you can't just send any json), [one can make it work](https://tkdodo.eu/blog/using-web-sockets-with-react-query) (the idea is to do `useQuery`   for the initial fetch, and then do subscriptions to receive updates - a sample code for this is [here](https://github.com/PaulKujawa/react-query-playground/blob/ffb9a8e23e8f2401c949de81f8485d85c0a240c6/client/src/repositories/books.tsx#L22-L52), sent by @PaulKujawa in [this comment](https://github.com/TanStack/query/issues/171#issuecomment-769733820))

@tannerlinsley (the Tan from TanStack) thinks implementing websocket support on react-query itself isn't a great fit, exactly because you need to carefully choose the shape of the messages to fit a schema, and react-query is supposed to work with any kind of messages. From TanStack/query#171:

In [this comment](https://github.com/TanStack/query/issues/171#issuecomment-647741294)

> After a lot of consideration and playing around with this concept, I don't believe it belongs in this library. I would be happy to help anyone build it for their own use cases, but it will not be making a first-class appearance in React Query for the time being.

And then in [this other](https://github.com/TanStack/query/issues/171#issuecomment-649712778)

> I hear you that the subscription library world is super sparse and janky if you ask me. Let me elaborate on a few more things that might help this discussion be more targeted.

> Apollo only "supports" subscriptions because they have a unified API on how subscriptions are interpreted (GraphQL) and the expectations behind them. Even so, Apollo (and just GraphQL) subscriptions for that matter still need an implementation layer that adheres to the spec, but actually powers the transactions. This is where there are GQL subscription plugins and layers made in sockets, http polling, grpc, etc. With that said, React Query doesn't force a spec upon you, and thus we cannot provide first class subscription plugins and implementors like Apollo does. This doesn't mean that it's not possible to use subscriptions (as a general concept) with React Query, but it does mean that you would have a different implementation for every combination of technology, eg. the Nozzle app uses sockets via Pusher and a custom hook that calls queryCache.invalidateQueries or queryCache.setQueryData from the events received. Once you change the socket implementation, the event shape/interface, or even what you ID your queries with, the entire custom hook changes.

He points out that a library that has some idea about the schema of the data is better suited to implement websocket support than react-query itself. So every rpc protocol on top of react-query will have a different way to handle subscriptions, but hopefully rspc might settle on a single, standardized way.

I'll probably prototype with this (out of tree) and if it's fruitful I can send a PR, but for now I'm not using react-query for subscriptions.

**Comment by oscartbeaumont** [comment]
I would be interested to see your PR but I don't think this is going to work because I don't think you fully understand rspc subscriptions. A subscription is a way for the server to push data to the client, identified by a key, and where the data is **_arbitrary_** (hence rspc assumes no format or shape for it). Remember the **_arbitrary_** part, it's the important one.

For example say you have a subscription that sends a message like "update data to B". For this usecase we could tie the subscription to React Query so that when a message is received we would update the query cache and the user could access it normally via a `useQuery` hook. This works because our subscription only holds a single discrete "thing". The `useQuery` hook would hold the most recent value of the "thing" and every subscription message would hold a modified version of the same discrete "thing". This style of subscription works for the design your proposing.

Now say you have a subscription that sends a message like "show popup notification with message X". Each value that is read from the subscription is a discrete "thing" (unlike the previous example) and so storing it into a `useQuery` which is designed to hold a single discrete "thing" is problematic.

A `useQuery` is also designed to support caching and reuse of a discrete "thing" but in this case, a subscription message has no value for that. By assuming all the messages send via a rspc subscription are for a single discrete "thing" we lose the ability to send **_arbitrary_** data via them and destroy a large amount of their usefulness. This design would also make subscriptions super inflexible which when building a library is something you want to avoid where possible.

What the article TkDodo wrote is using a Websocket for the express purpose of updating the React Query Cache with new data like the first example. From what I understand he doesn't account for the second example (and nor should he or React Query for that matter).

In technical terms rspc would need a stream/generator-style API. It was discussed (TanStack/query#418) and it was decided against supporting in React Query. I **fully** agree with this move from them because it feels out of scope of React Query even if it would be nice. That discussion also shows using an infinite query to work around this but I struggle the grasp the benefit of that for 99.999% of use cases. 

As far as I am concerned what you have described isn't the subscription system as much as it's a separate system on top of the subscription system which I have been refering to as the "invalidation system". Spacedrive has one of these built on top of rspc. The invalidate system could internally create a rspc subscription called something like `rspc.invalidate` (I am fairly sure I prevent anyone using `rspc` as a subrouter prefix) and using an internal format could communicate with `@rspc/react`/`@rspc/solid` to invalidate/update data.

Now if you reframe this conversion into building an invalidate system for rspc, it makes perfect sense to follow the architecture TkDodo wonderfully documented. However, dealing with invalidation on the Rust side brings another huge set of problems, namely, how does your Rust code tell the frontend to invalidate the query? Now you might think, well that seems easy, it's just a function call, right? Well, rspc is a library all about typesaftey and that is core to any feature it supports so you would need to come up with a typesafe API for invalidation in Rust and that just isn't possible because of rspc's use of string keys. There are some cool features on nightly that could make this work but they are a while off landing in stable and come with their own set of problems given rspc current design (although I would probably have forced it to work if they were stable).

To better explain my point in code:
```rust
ctx.invalidate("someQueryThatExists");
ctx.invalidate("thisQueryDoesn'tExistAndThisWillStillWork"); // This should be detectable and preventable in either a unit test or compiler error

ctx.invalidateWithData("someQueryThatExists", SomeQueryThatExistsArgs {});
ctx.invalidateWithData("someQueryThatExists", 42); // The data has the incorrect type based on query key. This should be detectable and preventable in either a unit test or compiler error
```

[Spacedrive](https://www.spacedrive.com/) has an `invalidate_query!` macro which allows us to do invalidation in a way we can make typesafe through a unit test but this is not a good enough developer experience that I am willing to support it in rspc so, for now, your on your own to build an invalidation system using the subscription primitive. Our system is defined [here](https://github.com/spacedriveapp/spacedrive/blob/main/core/src/api/utils/invalidate.rs) and [here](https://github.com/spacedriveapp/spacedrive/blob/c08622827caa9de53b24a39b53b339052ee4f320/packages/client/src/rspc.ts#L78) but I would caution you don't copy it unless you can actually understand what it's doing because it makes many compromises and assumptions (some of the which are documented as part of spacedriveapp/spacedrive#493).

For the future, I am working on some prototypes of a new API in Rust that would allow for typesafe invalidation among other things but I am not certain of many aspects of its design (mainly its usage of macros for large transformations to your code). I am hoping to have a beta of it within the next 2 months but it's still got many unanswered questions and may turn out to not be possible.

On a personal note, I would be careful @'ing people for issues that they aren't personally required in because many people are busy and don't need more notifications (If you really need to be able to navigate to their profile just hyperlink their GH).

**Comment by dlight** [comment]
> As far as I am concerned what you have described isn't the subscription system as much as it's a separate system on top of the subscription system which I have been refering to as the "invalidation system".

Indeed, I think this pretty much sums it. There's value in having a low-level subscription system (like the one that rspc currently have) and a high-level invalidation system (that can be built on top of the low level system).

Maybe the invalidation can even be on a separate npm package, like @rspc/react-invalidation.

And yeah you're right about the @s, sorry.

> [Spacedrive](https://www.spacedrive.com/) has an invalidate_query! macro which allows us to do invalidation in a way we can make typesafe through a unit test but this is not a good enough developer experience that I am willing to support it in rspc so, for now, your on your own to build an invalidation system using the subscription primitive. Our system is defined [here](https://github.com/spacedriveapp/spacedrive/blob/main/core/src/api/utils/invalidate.rs) and [here](https://github.com/spacedriveapp/spacedrive/blob/c08622827caa9de53b24a39b53b339052ee4f320/packages/client/src/rspc.ts#L78) but I would caution you don't copy it unless you can actually understand what it's doing because it makes many compromises and assumptions (some of the which are documented as part of https://github.com/spacedriveapp/spacedrive/pull/493).

That's pretty cool, thanks!
