### ISSUE TITLE
Export for Kotlin

### ISSUE THREAD

**Issue by hanssonduck** [oscartbeaumont/rspc#124]
Would it be possible to also export the procedures for Kotlin so they can be used in Android or even KMM development?

**Comment by oscartbeaumont** [comment]
The plan is to support this in the long term. Once [Specta](https://github.com/oscartbeaumont/specta) lands full support for Kotlin rspc can adopt it.

**Comment by SirMishaa** [comment]
Excellent idea, do you think for now we can write procedure manually and make request using https://grpc.io/docs/languages/kotlin/quickstart/ ?

**Comment by oscartbeaumont** [comment]
This is a common confusion but RPC is not GRPC. RPC stands for remote procedure call and is just the concept of requesting data from another device. GRPC on the over hand is a structured format for doing RPC.

rspc's API is far from compatible with GRPC especially because of the GRPC handles schema/field versioning.

Given rspc uses HTTP under the hood it would be fairly easy to make a custom client in any language, however you have to understand that the JSON format rspc uses isn't a stable API and will lickly go through changes in future updates. If you were to open source your Kotlin client I would be willing to help update it if that was the case.
