### ISSUE TITLE
Generate Types at compile time

### ISSUE THREAD

**Issue by turulix** [oscartbeaumont/rspc#209]
Any chance this could be done? :)

**Comment by oscartbeaumont** [comment]
Depends on what your goal is.

If your goal is so you don't need to startup your program you can use a unit tests to export the types. You should probably have this anyway as you will want to validate your rspc router is valid in a unit test (as I should show in the docs).

If your goal is to remove the runtime dependency on Specta, as far as I can tell this is basically impossible without impacting Specta's ability to have an ecosystem of 3rd party types, although i'm sure I will keep investigating new potential solutions.

What exactly is your goal with it being compile time?

**Comment by turulix** [comment]
Maybe compiletime isn't the correct term. Im sorry for that. My main problem is that im using a Dockerfile to build my backend and can't copy the file from the backend to the Frontend this way (I dont really want to compile it multiple times with different targets) I would love to have something like https://github.com/1Password/typeshare CLI which can just output the file without running the program or even compiling it (Im aware this is completely impossible with the current method). 

But it would be amazing if one could just define a function somewhere, put an annotation on the method, and get a typescript interface with all the methods that then call those functions or something along those lines

**Comment by oscartbeaumont** [comment]
[Specta](https://docs.rs/specta/latest/specta) is designed for runtime exporting because I think it is the right tradeoff and I can't see how rspc would be possible without it. When you use a static type exporter such as [Typeshare](https://github.com/1Password/typeshare), it has to guess the type from the tokens in the file which basically requires reprograming the Rust compilers type resolution code if you want to support anything other than simple types (which rspc requires for infering return types of closures). In Specta's current state, the only types that can trip it up are type aliases and there is some stuff coming in Specta v2 to improve this.

For example, if you had an rspc procedure returning `another()`, Specta would be able to resolve the type to `string` normally and `u32` when `cfg(debug_assertions)` (in non `--release` builds). Typeshare would have to somehow determine `demo()`'s return type  (which would require a system to be able to compute the `cfg`'s) and then deal with the logic to track the types flowing through the program (eg. that `another()` happens to return the same as `demo()`). This is obviously a complicated type but is more to show that Typeshare will have a lot more limitations than Specta.
```rust
use specta::Type;
use serde::Serialize;

fn demo() -> impl Type + Serialize {
    #[cfg(debug_assertions)]
    42
    #[cfg(not(debug_assertions))]
    "hello"
}

fn another() ->  impl Type + Serialize {
    demo()
}
```

I also don't think Typeshare even supports inference for function/closure results (probably for the previous reason) and honestly, even if it did I don't know how it could work with rspc. rspc enforces the `specta::Type` bound on the result of the user-defined functions so it know for a fact that every procedure can be typed. Typeshare would at best have to rely on codegen for this but it would be pretty messy if not impossible across crate boundaries due to Rust's orphan rule.

For Spacedrive we have been checking the `bindings.ts` into Git, cause it's good for code review and maybe that could help with your Docker builds.

**Comment by Ziothh** [comment]
@turulix If you **_really_** don't want to run the binary to generate types, you could always just use a `build.rs` script and run it with `cargo check`.

I have a project that only uses `specta` where I use such a build script.

Imho for `rspc` it's a bit cumbersome to do it this way and I'd just recommend to run your server once, like Oscart suggested.

Here's an example:

```toml
# Cargo.toml

[package]
name = "api"
version = "0.0.1"
build = "./src/build.rs"

[[bin]]
name = "api-bin"
path = "src/main.rs"

[lib]
name = "api"
path = "src/lib/mod.rs"

[dependencies]
serde = { ... }
rspc = { ... } 
specta = "x.x.x"

[build-dependencies]
# All dependencies needed for router: 
# e.g. rspc, serde, specta, ...
```

```rust
// router.rs

pub fn create_router() -> Router<MyCtx> {
  Router::<MyCtx>::new().build()
}
```

```rust
// build.rs
#[path = "./lib/mod.rs"]
mod api;

fn  main() {
  api::router::create_couter().export_ts("./foo/bar/baz.ts");
}
```
