### ISSUE TITLE
Question: Global state in Axum/rspc?

### ISSUE THREAD

**Issue by Trixxi** [oscartbeaumont/rspc#24]
"Per Request Context" seems to create a new context "per request", which is not what i need. 
In actix-web i can just create a "AppState(WebData)", and that state is shared between all requests.

A simple example with a global "request hit counter" would be appreciated.

**Comment by kkharji** [comment]
Maybe try `Arc<Mutex<WebData>>` or `Arc<WebData>`. it creates new arc reference for each request but the underlaying reference point to the same memory.

**Comment by Trixxi** [comment]
Thank you for your response.
I figured it out, was initially missing out "where" to set the data for the context, but then the rust compiler started yelling at me for not initializing the context in the Axum Handler.

So if i didnt mess up completely, this should be fine? It runs and functions
```rust
struct Ctx {
        pub counter: i32,
    }    

    let router = Router::<Arc<Mutex<Ctx>>>::new()
        .config(Config::new().export_ts_bindings("./ts"))
        .query("version", |mut ctx, arg: ()| {
            let mut ctx = ctx.lock().unwrap();

            ctx.counter += 1;

            format!("{}", ctx.counter)
        })
        .build();


    let router = Arc::new(router);
    let state: Arc<Mutex<Ctx>> = Arc::new(Mutex::new(Ctx {
        counter: 0,
    }));

    let app = axum::Router::new()
        .route("/rspc/:id", router.clone().axum_handler(|| {state}));```

**Comment by oscartbeaumont** [comment]
You have got it. You need to `Arc` your global state and if you require [interior mutability](https://doc.rust-lang.org/book/ch15-05-interior-mutability.html) you can use a `Mutex` as you have in the example above. For a hit counter, I would use an `Arc<AtomicU16>` but you probably intended this as an example so that's not something that will help in the real world ([view example here](https://github.com/oscartbeaumont/rspc/blob/main/examples/global_context.rs)).

It's worth noting actix-web's `AppState` will just be `Arc`ing your data under the hood anyway. I don't feel like it's worth adding an abstraction like Actix have for rspc because it just applies magic and removes a developers understanding of what is happening for no extra value, imo. I will however do some more work at documenting this as I can understand your confusion.

I am hoping to have actix-web support for the library within the week if you are interested.

As a side note, you could use Axum extensions (the equivalent of Actix's `AppState`) with rspc however I would not recommend doing this as it may cause runtime exceptions and has no added benifit over what you have done above.
